name: Test smbprotocol
on:
  push:
    branches:
    - master
    paths-ignore:
    - CHANGELOG.md
    - LICENSE
    - README.md

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Python 3.10.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install flake8
          flake8 .

      - name: Run unit tests
        run: |
          pytest tests/unit
